# ControllerRegistration object allows to register external controllers.
# See https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md.
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: os-coreos
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
  # primary: true|false
  # globallyEnabled: true|false # only valid if kind=Extension
  # reconcileTimeout: 30s # only valid if kind=Extension
  deployment:
    type: helm
    providerConfig:
      chart: |
        H4sIFAAAAAAA/yk...
      values:
        foo: bar
  # policy: OnDemand|Always
  # seedSelector:
  #   matchLabels:
  #     foo: bar
