# Seed cluster registration manifest into which the control planes of Shoot clusters will be deployed.
---
apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: my-seed
spec:
  provider:
    type: <provider-name> # e.g., aws, azure, gcp, ...
    region: europe-1
  # providerConfig:
  #   <some-provider-specific-config-for-the-seed>
# Optional, only needed if controlled by a Gardenlet running outside
# secretRef:
#   name: seed-secret
#   namespace: garden
# Configuration of backup object store provider into which the backups will be stored.
# If you don't want to have backups then don't specify the `.spec.backup` key.
  backup:
    provider: <provider-name> # e.g., aws, azure, gcp, ...
  # providerConfig:
  #   <some-provider-specific-config-for-the-backup-buckets>
    region: europe-1
    secretRef:
      name: backup-secret
      namespace: garden
  dns:
    ingressDomain: dev.my-seed.example.com
  networks: # seed and shoot networks must be disjunct
    nodes: 10.240.0.0/16
    pods: 10.241.128.0/17
    services: 10.241.0.0/17
  # shootDefaults:
  #   pods: 100.96.0.0/11
  #   services: 100.64.0.0/13
    blockCIDRs:
    - 169.254.169.254/32
  settings:
    excessCapacity:
      enabled: true # this seed will deploy excess-capacity-reservation pods
    scheduling:
      visible: true # the gardener-scheduler will consider this seed for shoots
    shootDNS:
      enabled: true # all shoots on this seed will use DNS, if disabled they'll just use the plain IPs/hostnames
# taints:
# - key: seed.gardener.cloud/protected # only shoots in the `garden` namespace can use this seed
# - key: <some-key>
# DEPRECATED: The below keys are deprecated in favor of the `.spec.settings` section. Please don't use them anymore and
# switch to the new seed settings.
# - key: seed.gardener.cloud/protected                    # only shoots in the `garden` namespace can use this seed
# - key: seed.gardener.cloud/invisible                    # the gardener-scheduler won't consider this seed for shoots
# - key: seed.gardener.cloud/disable-capacity-reservation # this seed will not deploy excess-capacity-reservation pods
# volume:
#  minimumSize: 20Gi
#  providers:
#  - purpose: etcd-main
#    name: flexvolume
