images:
  hyperkube: image-repository
bootstrapToken: hugo
kubernetesVersion: v1.17.0
configFilePath: /var/lib/cloud-config-downloader/downloads/cloud_config
worker:
  name: cpu-worker
  secretName: cloud-config-cpu-worker-ab234
  cloudConfig: generated-original-cloud-config-data
  command: /usr/bin/reload --path=<path>
  units:
  - kubelet.service
#  kubeletDataVolume:
#    name: vol1
#    size: 6262500000
#    type: gp2
