apiVersion: {{ include "hpaversion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: istiod
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
