apiVersion: {{ include "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: istiod
  labels:
{{ .Values.labels | toYaml | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod
subjects:
- kind: ServiceAccount
  name: istiod
  namespace: {{ .Release.Namespace }}
