apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
spec:
  ports:
  - name: https-sds # mTLS with k8s-signed cert
    port: 15012
  - name: https-webhook # validation and injection
    port: 443
    targetPort: 15017
  selector:
{{ .Values.labels | toYaml | indent 4 }}
