apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
{{ .Values.labels | toYaml | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
{{ .Values.labels  | toYaml | indent 4 }}
  ports:
  - name: status-port
    port: 15020
    targetPort: 15020
{{- if .Values.ports }}
{{ toYaml .Values.ports | indent 2 }}
{{- end }}
